### ISSUE TITLE
Add Windows 7 EOL

### ISSUE THREAD

**Issue by CoburnFuse** [torchgm/TechSupportGUI#1]
Windows 7 is EOL, It should give a warning before opening the program. Like first a popup (where you have to wait like 5 seconds) and then you can press OK.

**Comment by Erisa** [comment]
Could also do similar for the W10 versions that are EOL?

**Comment by torchgm** [comment]
yesyesyes alright but it probably won't be a popup since users seem to be too useless to actually realise they can be dismissed, it'll more likely just be an angry message in the console

**Comment by CoburnFuse** [comment]
Or you know, do both since pop ups annoy people and its dumb to stay on EOL windows

**Comment by torchgm** [comment]
nope that would be silly the whole point of the app is to provide tech support, not upgrade advice, however i have added it as a console message anyway now so go do a thing and build it and see if it works and yes @Erisa i did the thingy too
